import { Card } from '@/components/ui/Card'
import { useSessionStore } from '@/store/useSessionStore'
import { useTaskStore } from '@/store/useTaskStore'
import { categoryDistribution, computeStreak, dailyFocusMinutes, totalFocusMinutes, weeklyFocusMinutes } from '@/utils/statistics'
import { weekdayLabels } from '@/utils/date'
import { formatDuration } from '@/utils/timer'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const colors = ['#00ffc6', '#7c83fd', '#f5b971', '#ff7b8b', '#8b929a']

export function StatisticsPage() {
  const sessions = useSessionStore((state) => state.sessions)
  const tasks = useTaskStore((state) => state.tasks)
  const weekly = weeklyFocusMinutes(sessions).map((minutes, index) => ({ name: weekdayLabels()[index], minutes: Math.round(minutes) }))
  const daily = dailyFocusMinutes(sessions, 14)
  const categories = categoryDistribution(sessions, tasks)
  const streak = computeStreak(sessions)
  return <div className="space-y-5"><div><p className="text-sm text-accent">Your rhythm</p><h1 className="mt-1 text-3xl font-semibold">Statistics</h1><p className="mt-2 text-sm text-muted">Small consistent sessions compound.</p></div><div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-xs text-muted">Total focus</p><p className="mt-2 text-2xl font-semibold">{formatDuration(totalFocusMinutes(sessions))}</p></Card><Card><p className="text-xs text-muted">Best streak</p><p className="mt-2 text-2xl font-semibold">{streak.best} days</p></Card><Card><p className="text-xs text-muted">Sessions logged</p><p className="mt-2 text-2xl font-semibold">{sessions.filter((item) => item.type === 'focus').length}</p></Card></div><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card><h2 className="text-lg font-semibold">This week</h2><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={weekly}><CartesianGrid stroke="var(--chart-grid)" vertical={false} /><XAxis dataKey="name" tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12 }} /><Bar dataKey="minutes" fill="var(--accent)" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></Card><Card><h2 className="text-lg font-semibold">By category</h2><div className="mt-3 h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="minutes" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={3}>{categories.map((item, index) => <Cell key={item.name} fill={colors[index]} />)}</Pie><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12 }} /></PieChart></ResponsiveContainer></div><div className="space-y-2">{categories.map((item, index) => <div key={item.name} className="flex justify-between text-xs"><span className="text-muted"><i className="mr-2 inline-block h-2 w-2 rounded-full" style={{ background: colors[index] }} />{item.name}</span><span>{item.minutes}m</span></div>)}</div></Card></div><Card><h2 className="text-lg font-semibold">Last 14 days</h2><div className="mt-4 grid grid-cols-7 gap-2 sm:grid-cols-14">{daily.map((item) => <div key={item.date} className="group"><div className="h-20 rounded-lg bg-elevated p-1"><div className="h-full rounded-md bg-accent transition-opacity group-hover:opacity-70" style={{ opacity: item.minutes ? Math.min(1, .2 + item.minutes / 120) : .08 }} /></div><p className="mt-1 text-center text-[10px] text-muted">{item.date.slice(8)}</p></div>)}</div></Card></div>
}