import type { en } from './en'

export const kk: { [K in keyof typeof en]: string } = {
  'focus.progress': '{count}% орындалды',
  'nav.dashboard': 'Басты бет', 'nav.focus': 'Фокус', 'nav.tasks': 'Тапсырмалар', 'nav.statistics': 'Статистика', 'nav.settings': 'Баптаулар', 'nav.stats': 'Статистика', 'nav.primary': 'Негізгі навигация', 'nav.mobile': 'Мобильді навигация', 'profile.role': 'Бағдарламалық инженерия студенті',
  'common.cancel': 'Бас тарту', 'common.save': 'Өзгерістерді сақтау', 'common.dismiss': 'Жабу', 'common.close': 'Диалогты жабу', 'common.today': 'Бүгін', 'common.noData': 'Әзірге дерек жоқ', 'common.hoursMinutes': '{hours} сағ {minutes} мин', 'common.minutes': '{count} мин', 'common.days': '{count} күн', 'common.sessions': '{count} сессия', 'common.tasks': '{count} тапсырма', 'common.dayOne': '{count} күн', 'common.dayFew': '{count} күн', 'common.dayMany': '{count} күн', 'common.sessionOne': '{count} сессия', 'common.sessionFew': '{count} сессия', 'common.sessionMany': '{count} сессия', 'common.taskOne': '{count} тапсырма', 'common.taskFew': '{count} тапсырма', 'common.taskMany': '{count} тапсырма',
  'dashboard.eyebrow': 'Терең жұмысқа орын босатыңыз.', 'dashboard.subtitle': 'Назарды нәтижеге айналдыратын тыныш кеңістік.', 'dashboard.newTask': 'Жаңа тапсырма', 'dashboard.sessionsToday': 'Бүгінгі сессиялар', 'dashboard.currentStreak': 'Ағымдағы серия', 'dashboard.tasksCompleted': 'Орындалған тапсырмалар', 'dashboard.focusPlan': 'Фокус жоспарыңыз', 'dashboard.viewStats': 'Статистиканы көру', 'dashboard.everythingComplete': 'Барлығы орындалды. Керемет жұмыс.', 'dashboard.focusTime': 'Фокус уақыты', 'dashboard.pomodoros': 'помодоро',
  'timer.focus': 'Фокус', 'timer.focusSession': 'Фокус сессиясы', 'timer.shortBreak': 'Қысқа үзіліс', 'timer.longBreak': 'Ұзақ үзіліс', 'timer.start': 'Фокусты бастау', 'timer.pause': 'Үзіліс', 'timer.resume': 'Жалғастыру', 'timer.reset': 'Қалпына келтіру', 'timer.skip': 'Өткізу', 'timer.live': 'Жұмыс істеп тұр', 'timer.paused': 'Үзілісте', 'timer.break': 'Үзіліс', 'timer.focusMode': 'Фокус режимі', 'timer.sessionComplete': 'Сессия аяқталды', 'timer.focusComplete': 'Фокус аяқталды', 'timer.breakComplete': 'Үзіліс аяқталды', 'timer.timeForRecharge': 'Демалатын уақыт.',
  'focus.backDashboard': 'Басты бет', 'focus.taskLabel': 'Фокус тапсырмасы', 'focus.chooseTask': 'Қазір немен айналысып жатырсыз?', 'focus.createTask': 'Алдымен белсенді тапсырма жасаңыз.', 'focus.chooseTaskToBegin': 'Бастау үшін тапсырманы таңдаңыз', 'focus.exit': 'Фокус режимінен шығу', 'focus.enterFullscreen': 'Толық экран', 'focus.exitFullscreen': 'Толық экраннан шығу', 'focus.endSession': 'Сессияны аяқтау', 'focus.startBreak': 'Үзілісті бастау', 'focus.finish': 'Дайын', 'focus.greatWork': 'Керемет жұмыс.', 'focus.focused': '+{count} мин фокус', 'focus.soundOn': 'Дыбыс қосулы', 'focus.soundOff': 'Дыбыс өшірулі', 'focus.muteSound': 'Аяқталу дыбысын өшіру', 'focus.enableSound': 'Аяқталу дыбысын қосу', 'focus.dndReminder': 'Терең фокус үшін құрылғыңызда «Мазаламаңыз» режимін қосуды ойлаңыз.', 'focus.dismissReminder': '«Мазаламаңыз» еске салуын жабу', 'focus.shortcutHint': 'Бос орын — үзіліс/жалғастыру · F — фокус режимі · Esc — шығу', 'focus.fullscreenTimer': 'Толық экран таймері',
  'tasks.eyebrow': 'Тапсырмалар жүйесі', 'tasks.title': 'Тапсырмалар', 'tasks.subtitle': 'Жұмыс көлемін фокус сессияларына айналдырыңыз.', 'tasks.new': 'Жаңа тапсырма', 'tasks.noTasks': 'Бұл көріністе тапсырмалар жоқ.', 'tasks.all': 'Барлығы', 'tasks.active': 'Белсенді', 'tasks.completed': 'Орындалған', 'tasks.sort': 'Сұрыптау', 'tasks.sortPriority': 'Басымдық', 'tasks.sortDate': 'Күн', 'tasks.sortPomodoros': 'Помодоро', 'tasks.actions': 'Тапсырма әрекеттері', 'tasks.focus': 'Фокус', 'tasks.edit': 'Өзгерту', 'tasks.delete': 'Жою', 'tasks.complete': '{title} аяқтау', 'tasks.reopen': '{title} белсенді ету', 'tasks.created': 'Тапсырма жасалды', 'tasks.updated': 'Тапсырма жаңартылды', 'tasks.deleted': 'Тапсырма жойылды', 'tasks.completedToast': 'Тапсырма аяқталды', 'tasks.completedPomodoros': '{completed}/{estimated} помодоро',
  'modal.newTask': 'Жаңа тапсырма', 'modal.editTask': 'Тапсырманы өзгерту', 'modal.description': 'Келесі маңызды қадамды көз алдыңызда ұстаңыз.', 'modal.title': 'Атауы', 'modal.titlePlaceholder': 'Неге көңіл бөлу керек?', 'modal.taskDescription': 'Сипаттама', 'modal.descriptionPlaceholder': 'Қосымша контекст', 'modal.category': 'Санат', 'modal.priority': 'Басымдық', 'modal.pomodoros': 'Жоспарланған помодоро', 'modal.dueDate': 'Мерзімі', 'modal.cancel': 'Бас тарту', 'modal.create': 'Тапсырма жасау', 'modal.save': 'Өзгерістерді сақтау',
  'statistics.eyebrow': 'Ырғағыңыз', 'statistics.title': 'Статистика', 'statistics.subtitle': 'Тұрақты шағын сессиялар үлкен нәтижеге әкеледі.', 'statistics.totalFocus': 'Жалпы фокус', 'statistics.bestStreak': 'Ең ұзақ серия', 'statistics.sessionsLogged': 'Сессиялар', 'statistics.completedTasks': 'Орындалған тапсырмалар', 'statistics.thisWeek': 'Апталық белсенділік', 'statistics.byCategory': 'Фокус бөлінісі', 'statistics.last14Days': 'Соңғы 14 күн', 'statistics.minutes': '{count} мин',
  'settings.eyebrow': 'Жүйені өзіңізге бейімдеңіз', 'settings.title': 'Баптаулар', 'settings.timer': 'Таймер', 'settings.focusMinutes': 'Фокус минуттары', 'settings.shortBreak': 'Қысқа үзіліс', 'settings.longBreak': 'Ұзақ үзіліс', 'settings.longBreakAfter': 'Ұзақ үзіліске дейін', 'settings.applyDurations': 'Ұзақтықты қолдану', 'settings.focusMode': 'Фокус режимі', 'settings.autoFocusMode': 'Фокус режиміне автоматты кіру', 'settings.autoFocusModeDescription': 'Фокус таймері басталғанда алаңдатпайтын көріністі ашу.', 'settings.dndReminder': '«Мазаламаңыз» еске салуын көрсету', 'settings.dndReminderDescription': 'Құрылғыдағы «Мазаламаңыз» режимін қосуды еске салу.', 'settings.autoFullscreen': 'Толық экранға автоматты кіру', 'settings.autoFullscreenDescription': 'Фокус режимі ашылғанда браузердің толық экранын сұрау.', 'settings.preferences': 'Параметрлер', 'settings.autoBreaks': 'Үзілістерді автоматты бастау', 'settings.autoBreaksDescription': 'Келесі үзіліске автоматты түрде өту.', 'settings.autoFocus': 'Фокусты автоматты бастау', 'settings.autoFocusDescription': 'Келесі фокус сессиясын автоматты бастау.', 'settings.completionSound': 'Аяқталу дыбысы', 'settings.notifications': 'Жұмыс үстелі хабарламалары', 'settings.appearance': 'Сыртқы көрініс', 'settings.theme': 'Тақырып', 'settings.dark': 'Қараңғы', 'settings.light': 'Жарық', 'settings.system': 'Жүйелік', 'settings.language': 'Тіл', 'settings.languageEnglish': 'English', 'settings.languageRussian': 'Русский', 'settings.languageKazakh': 'Қазақша', 'settings.notificationsUnavailable': 'Хабарламалар қолжетімсіз', 'settings.allowNotifications': 'Бұл функцияны пайдалану үшін браузерде хабарламаларға рұқсат беріңіз.',
  'toast.sessionCompleted': 'Сессия аяқталды', 'toast.sessionLogged': 'Сессия өнімділік тарихына қосылды.', 'toast.dismiss': 'Хабарламаны жабу', 'category.Study': 'Оқу', 'category.Work': 'Жұмыс', 'category.Personal': 'Жеке', 'category.Coding': 'Бағдарламалау', 'category.Other': 'Басқа', 'priority.High': 'Жоғары', 'priority.Medium': 'Орташа', 'priority.Low': 'Төмен',
}
