import type { en } from './en'

export const ru: { [K in keyof typeof en]: string } = {
  'focus.progress': '{count}% завершено',
  'nav.dashboard': 'Главная', 'nav.focus': 'Фокус', 'nav.tasks': 'Задачи', 'nav.statistics': 'Статистика', 'nav.settings': 'Настройки', 'nav.stats': 'Статистика', 'nav.primary': 'Основная навигация', 'nav.mobile': 'Мобильная навигация', 'profile.role': 'Студент программной инженерии',
  'common.cancel': 'Отмена', 'common.save': 'Сохранить изменения', 'common.dismiss': 'Закрыть', 'common.close': 'Закрыть диалог', 'common.today': 'Сегодня', 'common.noData': 'Пока нет данных', 'common.hoursMinutes': '{hours} ч {minutes} мин', 'common.minutes': '{count} мин', 'common.days': '{count} дн.', 'common.sessions': '{count} сессий', 'common.tasks': '{count} задач', 'common.dayOne': '{count} день', 'common.dayFew': '{count} дня', 'common.dayMany': '{count} дней', 'common.sessionOne': '{count} сессия', 'common.sessionFew': '{count} сессии', 'common.sessionMany': '{count} сессий', 'common.taskOne': '{count} задача', 'common.taskFew': '{count} задачи', 'common.taskMany': '{count} задач',
  'dashboard.eyebrow': 'Освободите место для глубокой работы.', 'dashboard.subtitle': 'Спокойное пространство, где внимание превращается в результат.', 'dashboard.newTask': 'Новая задача', 'dashboard.sessionsToday': 'Сессий сегодня', 'dashboard.currentStreak': 'Текущая серия', 'dashboard.tasksCompleted': 'Завершено задач', 'dashboard.focusPlan': 'Ваш план фокуса', 'dashboard.viewStats': 'Статистика', 'dashboard.everythingComplete': 'Всё выполнено. Отличная работа.', 'dashboard.focusTime': 'Время фокуса', 'dashboard.pomodoros': 'помодоро',
  'timer.focus': 'Фокус', 'timer.focusSession': 'Сессия фокуса', 'timer.shortBreak': 'Короткий перерыв', 'timer.longBreak': 'Длинный перерыв', 'timer.start': 'Начать фокус', 'timer.pause': 'Пауза', 'timer.resume': 'Продолжить', 'timer.reset': 'Сбросить', 'timer.skip': 'Пропустить', 'timer.live': 'Идёт', 'timer.paused': 'Пауза', 'timer.break': 'Перерыв', 'timer.focusMode': 'Режим фокуса', 'timer.sessionComplete': 'Сессия завершена', 'timer.focusComplete': 'Фокус завершён', 'timer.breakComplete': 'Перерыв завершён', 'timer.timeForRecharge': 'Время восстановить силы.',
  'focus.backDashboard': 'Главная', 'focus.taskLabel': 'Задача фокуса', 'focus.chooseTask': 'Над чем вы работаете?', 'focus.createTask': 'Сначала создайте активную задачу.', 'focus.chooseTaskToBegin': 'Выберите задачу, чтобы начать', 'focus.exit': 'Выйти из режима фокуса', 'focus.enterFullscreen': 'Полный экран', 'focus.exitFullscreen': 'Выйти из полного экрана', 'focus.endSession': 'Завершить сессию', 'focus.startBreak': 'Начать перерыв', 'focus.finish': 'Готово', 'focus.greatWork': 'Отличная работа.', 'focus.focused': '+{count} мин фокуса', 'focus.soundOn': 'Звук включён', 'focus.soundOff': 'Звук выключен', 'focus.muteSound': 'Выключить звук завершения', 'focus.enableSound': 'Включить звук завершения', 'focus.dndReminder': 'Для глубокого фокуса включите режим «Не беспокоить» на устройстве.', 'focus.dismissReminder': 'Закрыть напоминание «Не беспокоить»', 'focus.shortcutHint': 'Пробел — пауза/продолжение · F — режим фокуса · Esc — выход', 'focus.fullscreenTimer': 'Таймер в полном экране',
  'tasks.eyebrow': 'Система задач', 'tasks.title': 'Задачи', 'tasks.subtitle': 'Превратите нагрузку в сфокусированные сессии.', 'tasks.new': 'Новая задача', 'tasks.noTasks': 'В этом представлении нет задач.', 'tasks.all': 'Все', 'tasks.active': 'Активные', 'tasks.completed': 'Завершённые', 'tasks.sort': 'Сортировка', 'tasks.sortPriority': 'Приоритет', 'tasks.sortDate': 'Дата', 'tasks.sortPomodoros': 'Помодоро', 'tasks.actions': 'Действия задачи', 'tasks.focus': 'Фокус', 'tasks.edit': 'Изменить', 'tasks.delete': 'Удалить', 'tasks.complete': 'Завершить {title}', 'tasks.reopen': 'Вернуть {title} в активные', 'tasks.created': 'Задача создана', 'tasks.updated': 'Задача обновлена', 'tasks.deleted': 'Задача удалена', 'tasks.completedToast': 'Задача завершена', 'tasks.completedPomodoros': '{completed}/{estimated} помодоро',
  'modal.newTask': 'Новая задача', 'modal.editTask': 'Изменить задачу', 'modal.description': 'Держите следующий важный шаг перед глазами.', 'modal.title': 'Название', 'modal.titlePlaceholder': 'На чём сосредоточиться?', 'modal.taskDescription': 'Описание', 'modal.descriptionPlaceholder': 'Дополнительный контекст', 'modal.category': 'Категория', 'modal.priority': 'Приоритет', 'modal.pomodoros': 'План помодоро', 'modal.dueDate': 'Срок', 'modal.cancel': 'Отмена', 'modal.create': 'Создать задачу', 'modal.save': 'Сохранить изменения',
  'statistics.eyebrow': 'Ваш ритм', 'statistics.title': 'Статистика', 'statistics.subtitle': 'Небольшие регулярные сессии дают накопительный эффект.', 'statistics.totalFocus': 'Всего фокуса', 'statistics.bestStreak': 'Лучшая серия', 'statistics.sessionsLogged': 'Сессии', 'statistics.completedTasks': 'Завершённые задачи', 'statistics.thisWeek': 'Активность за неделю', 'statistics.byCategory': 'Распределение фокуса', 'statistics.last14Days': 'Последние 14 дней', 'statistics.minutes': '{count} мин',
  'settings.eyebrow': 'Настройте систему под себя', 'settings.title': 'Настройки', 'settings.timer': 'Таймер', 'settings.focusMinutes': 'Минуты фокуса', 'settings.shortBreak': 'Короткий перерыв', 'settings.longBreak': 'Длинный перерыв', 'settings.longBreakAfter': 'Длинный перерыв после', 'settings.applyDurations': 'Применить длительность', 'settings.focusMode': 'Режим фокуса', 'settings.autoFocusMode': 'Автоматически входить в режим фокуса', 'settings.autoFocusModeDescription': 'Открывать режим без отвлечений при запуске фокуса.', 'settings.dndReminder': 'Показывать напоминание «Не беспокоить»', 'settings.dndReminderDescription': 'Напоминать включить системный режим «Не беспокоить».', 'settings.autoFullscreen': 'Автоматически включать полный экран', 'settings.autoFullscreenDescription': 'Запрашивать полный экран браузера при открытии режима фокуса.', 'settings.preferences': 'Параметры', 'settings.autoBreaks': 'Автоматически начинать перерывы', 'settings.autoBreaksDescription': 'Переходить к следующему перерыву автоматически.', 'settings.autoFocus': 'Автоматически начинать фокус', 'settings.autoFocusDescription': 'Автоматически запускать следующую фокус-сессию.', 'settings.completionSound': 'Звук завершения', 'settings.notifications': 'Уведомления на рабочем столе', 'settings.appearance': 'Внешний вид', 'settings.theme': 'Тема', 'settings.dark': 'Тёмная', 'settings.light': 'Светлая', 'settings.system': 'Системная', 'settings.language': 'Язык', 'settings.languageEnglish': 'English', 'settings.languageRussian': 'Русский', 'settings.languageKazakh': 'Қазақша', 'settings.notificationsUnavailable': 'Уведомления недоступны', 'settings.allowNotifications': 'Разрешите уведомления в браузере, чтобы использовать эту функцию.',
  'toast.sessionCompleted': 'Сессия завершена', 'toast.sessionLogged': 'Сессия добавлена в историю продуктивности.', 'toast.dismiss': 'Закрыть уведомление', 'category.Study': 'Учёба', 'category.Work': 'Работа', 'category.Personal': 'Личное', 'category.Coding': 'Разработка', 'category.Other': 'Другое', 'priority.High': 'Высокий', 'priority.Medium': 'Средний', 'priority.Low': 'Низкий',
}
